# Generated by Django 3.2.11 on 2022-01-29 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarMarketApp', '0002_auto_20220128_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seller_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
